---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: build-alpine
  image: nephatrine/nxbuilder:alpine
  commands:
  - sudo apk add curl-dev
  - sudo chown -R packager .
  - make
  - tar -C release -czvf q2admin-nxmod_x86_64-alpine-linux-musl.tar.gz game.so
  depends_on:
  - submodules
- name: publish
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea-api
    base_url: https://code.nephatrine.net
    files: q2admin-nxmod_x86_64-alpine-linux-musl.tar.gz
  depends_on:
  - build-alpine
  when:
    event:
    - promote
    - tag

---
kind: pipeline
name: notify

steps:
- name: notify-status
  image: appleboy/drone-discord
  failure: ignore
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-quake2-id
    webhook_token:
      from_secret: wh-quake2-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: dd4b6f22363045e961c97cf0705eba15aa9a68e5e0d14b09cc3eb84265079da5

...
