---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: nephatrine/nxbuilder:alpine
  commands:
  - sudo chown -R packager .
  - git submodule update --init --recursive
- name: build-alpine
  image: nephatrine/nxbuilder:alpine
  commands:
  - sudo apk update
  - sudo apk add curl-dev
  - make
  - tar -czvf q2admin-nxmod_x86_64-alpine-linux-musl.tar.gz -C release game.so
  - tar -czvf q2admin-nxmod_noarch.tar.gz q2*.txt q2*.json
  - make clean
  depends_on:
  - submodules
- name: build-ubuntu
  image: nephatrine/nxbuilder:ubuntu
  commands:
  - sudo apt-get update
  - sudo apt-get install libcurl4-openssl-dev
  - CFLAGS="-D_GNU_SOURCE" make
  - tar -czvf q2admin-nxmod_x86_64-ubuntu-linux-gnu.tar.gz -C release game.so
  - make clean
  depends_on:
  - build-alpine
- name: build-redhat
  image: nephatrine/nxbuilder:almalinux
  commands:
  - sudo dnf install libcurl-devel
  - CFLAGS="-D_GNU_SOURCE -m64" LDFLAGS="-m64" make
  - tar -czvf q2admin-nxmod_x86_64-redhat-linux-gnu.tar.gz -C release game.so
  - make clean
  depends_on:
  - build-ubuntu
- name: publish-web
  image: alpine/curl
  environment:
    WEBDAV_USERNAME:
      from_secret: webdav-user
    WEBDAV_PASSWORD:
      from_secret: webdav-pass
  commands:
  - curl -T 'q2admin-nxmod_{x86_64-alpine-linux-musl,x86_64-redhat-linux-gnu,x86_64-ubuntu-linux-gnu,noarch}.tar.gz' --user "$WEBDAV_USERNAME:$WEBDAV_PASSWORD" 'https://files.nephatrine.net/archives/'
  depends_on:
  - build-redhat
  when:
    event:
      exclude:
      - pull_request
- name: publish-gitea
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea-api
    base_url: https://code.nephatrine.net
    files:
    - q2admin-nxmod_x86_64-alpine-linux-musl.tar.gz
    - q2admin-nxmod_x86_64-redhat-linux-gnu.tar.gz
    - q2admin-nxmod_x86_64-ubuntu-linux-gnu.tar.gz
    - q2admin-nxmod_noarch.tar.gz
  depends_on:
  - build-redhat
  when:
    event:
    - tag

---
kind: pipeline
name: notify

steps:
- name: notify-status
  image: appleboy/drone-discord
  failure: ignore
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-quake2-id
    webhook_token:
      from_secret: wh-quake2-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: c4095699cd5e825a0dd286b6186db55b6c01dc5b267377c89feb9385486f3cfa

...
